import Badge from "../components/Badge";
import BaseAlert from "../components/BaseAlert";
import BaseButton from "../components/BaseButton";
import BaseCheckbox from "../components/BaseCheckbox";
import BaseInput from "../components/BaseInput";
import BaseDropdown from "../components/BaseDropdown";
import BaseNav from "../components/BaseNav";
import BasePagination from "../components/BasePagination";
import BasePaginationCustom from "../components/BasePaginationCustom";
import BaseProgress from "../components/BaseProgress";
import BaseRadio from "../components/BaseRadio";
import BaseSlider from "../components/BaseSlider";
import BaseSwitch from "../components/BaseSwitch";
import BaseTable from "../components/BaseTable";
import BaseTableCustom from "../components/BaseTableCustom";
import BaseHeader from "../components/BaseHeader";
import Card from "../components/Card";
import StatsCard from "../components/StatsCard";
import Modal from "../components/Modal";
import TabPane from "../components/Tabs/TabPane";
import Tabs from "../components/Tabs/Tabs";
import BaseDatatables from "../components/BaseDatatables";
import ButtonHeader from "../components/ButtonHeader.vue";
import DropdownCustom from "../components/DropdownCustom.vue";
import ButtonDropdownCustom from "../components/ButtonDropdownCustom.vue";
import ItemDropdownCustom from "../components/ItemDropdownCustom.vue";
import TextBasedCaptcha from "../components/TextBasedCaptcha.vue";
import DataTableCustom from "../components/DataTable/DataTableCustom.vue";
import BaseHeaderBody from "../components/BaseHeaderBody.vue";

export default {
  install(Vue) {
    Vue.component(Badge.name, Badge);
    Vue.component(BaseAlert.name, BaseAlert);
    Vue.component(BaseButton.name, BaseButton);
    Vue.component(BaseInput.name, BaseInput);
    Vue.component(BaseNav.name, BaseNav);
    Vue.component(BaseDropdown.name, BaseDropdown);
    Vue.component(BaseCheckbox.name, BaseCheckbox);
    Vue.component(BasePagination.name, BasePagination);
    Vue.component(BasePaginationCustom.name, BasePaginationCustom);
    Vue.component(BaseProgress.name, BaseProgress);
    Vue.component(BaseRadio.name, BaseRadio);
    Vue.component(BaseSlider.name, BaseSlider);
    Vue.component(BaseSwitch.name, BaseSwitch);
    Vue.component(BaseTable.name, BaseTable);
    Vue.component(BaseTableCustom.name, BaseTableCustom);
    Vue.component(BaseHeader.name, BaseHeader);
    Vue.component(Card.name, Card);
    Vue.component(StatsCard.name, StatsCard);
    Vue.component(Modal.name, Modal);
    Vue.component(TabPane.name, TabPane);
    Vue.component(Tabs.name, Tabs);
    Vue.component(BaseDatatables.name, BaseDatatables);
    Vue.component(ButtonHeader.name, ButtonHeader);
    Vue.component(DropdownCustom.name, DropdownCustom);
    Vue.component(ButtonDropdownCustom.name, ButtonDropdownCustom);
    Vue.component(ItemDropdownCustom.name, ItemDropdownCustom);
    Vue.component(TextBasedCaptcha.name, TextBasedCaptcha);
    Vue.component(DataTableCustom.name, DataTableCustom);
    Vue.component(BaseHeaderBody.name, BaseHeaderBody);
  },
};
